#!/bin/sh

# Can run sed on svg files to update colors
# hardcoded values in inkscape
GradStart=fad028
GradEnd=856a02
# white gradients overwrite the black ones
wGradStart=ffffff
wGradEnd=999999ff
pieces=(
  +b.svg  b.svg  g.svg  k.svg  +l.svg  l.svg  +n.svg  n.svg  +p.svg  p.svg  +r.svg  r.svg  +s.svg  s.svg
  cn.svg # avoid cn for now as scour generates a buggy corner
   soldier.svg a.svg i.svg u.svg c.svg +a.svg +i.svg +u.svg +c.svg # cannon shogi exclusives
  q.svg) # chess exclusive

chupieces=(leopard copper elephant chariot bishop tiger phoenix kirin sidemover verticalmover lion gobetween ox stag boar falcon prince eagle whale whitehorse
rookpromoted dragonpromoted horsepromoted lionpromoted queenpromoted bishoppromoted elephantpromoted sidemoverpromoted verticalmoverpromoted promotedpawn
)

declare -A lishogicss=(["+b"]="horse" ["b"]="bishop" ["g"]="gold" ["k"]="king" ["+l"]="promotedlance" ["l"]="lance" ["+n"]="promotedknight" ["n"]="knight" ["+p"]="tokin" ["p"]="pawn" ["r"]="rook" ["+r"]="dragon" ["+s"]="promotedsilver" ["s"]="silver" ["q"]="queen")

ODIR=./out/
OCSS=outfile.css
CHUCSS=chu.css
TORICSS=tori.css
LISHOGICSS=lishogi.css
LICHESSCSS=lichess.css
CannonShogiCSS=cannonshogi.css
if ! command -v scour &> /dev/null; then echo "Scour not found (svg simplifier)" ; exit 1 ; fi

# input file name , base64 value
emitcss() {
  echo "$1 {"
  echo "background-image: url(\"data:image/svg+xml;base64,$2\")!important; }"
}
# Output = (key , p , B64w , B64b)
simplifySVG() { name=$1 ; svg=$2
    b=$ODIR/b$name
    w=$ODIR/w$name
    # optimise svg, often divides size by 4
    scour -i $svg -o $b --remove-metadata #   inkscape --export-type=svg --export-filename=$b $svg
    # write white file by updating gradients in rgba (ff = white)
    sed "s/$GradStart/$wGradStart/g ; s/$GradEnd/$wGradEnd/g" $b > $w

    key=${svg%.svg}
    p=${lishogicss[$key]}
    B64w=$(base64 -w 0 $w)
    B64b=$(base64 -w 0 $b)
}

# inkscape --actions "select-all;transform-rotate:90;export-filename:out.svg;export-do" input.svg
toriPieces=(s ps l r k p c f pf)
genTori() {
  echo '/* Autogenerated by svgtocss, do not edit! */' >> $TORICSS
  echo "@-moz-document domain("pychess.org") {" >> $TORICSS
  for p in ${toriPieces[@]}; do
    file=toriPieces/$p.svg
    w=$ODIR/toriPieces/w$p.svg
    b=$ODIR/toriPieces/b$p.svg
    scour -i $file -o $w --remove-metadata
    # generate opposite pieces by 180degree rotation
    inkscape --actions "select-all; transform-rotate:180; export-filename:$b;export-do" $w
    B64w=$(base64 -w 0 $w)
    B64b=$(base64 -w 0 $b)
    # pychess
    emitcss ".tori piece.$p-piece.white.ally"  $B64w >> $TORICSS
    emitcss ".tori piece.$p-piece.white.enemy" $B64b >> $TORICSS
    emitcss ".tori piece.$p-piece.black.ally"  $B64w >> $TORICSS
    emitcss ".tori piece.$p-piece.black.enemy" $B64b >> $TORICSS
  done
  echo "}" >> $TORICSS
}

genCHU() {
# echo '/* Autogenerated by svgtocss, do not edit! */' >> $CHUCSS
# echo "@-moz-document domain("lishogi.org") {" >> $CHUCSS
  sed '$d ; s/kyoto/chu/g' $LISHOGICSS > $CHUCSS # delete last line and reuse shogi pieces where possible
  # echo "${f[@]/*/'prefix'&'suffix'}"
  for piecename in ${chupieces[@]}; do
    file=chushogipieces/$piecename.svg
    if [ ! -f $file ]; then continue; fi
    simplifySVG $piecename $file
    p=$piecename

    emitcss "piece.$p.sente,
    .v-chushogi piece.$p.sente,
    .v-chushogi .sg-wrap.orientation-sente piece.$p.sente,
    .v-chushogi .sg-wrap.orientation-gote piece.$p.sente" $B64b >> $CHUCSS
    emitcss "piece.$p.gote,
    .v-chushogi piece.$p.gote,
    .v-chushogi .sg-wrap.orientation-sente piece.$p.gote,
    .v-chushogi .sg-wrap.orientation-gote piece.$p.gote" $B64w >> $CHUCSS
  done
  echo "}" >> $CHUCSS
}

genAll() {
  echo '/* Autogenerated by svgtocss, do not edit! */' > $OCSS
  echo '/* Autogenerated by svgtocss, do not edit! */' > $LISHOGICSS
  echo '/* Autogenerated by svgtocss, do not edit! */' > $CannonShogiCSS
  echo '/* Autogenerated by svgtocss, do not edit! */' > $LICHESSCSS
  echo "@-moz-document domain("lichess.org") {" >> $LICHESSCSS
  echo "@-moz-document domain("lshogi.org") {" >> $LISHOGICSS
  echo "@-moz-document domain("pychess.org") {" >> $CannonShogiCSS

  for svg in ${pieces[@]}; do
    name=$(tr + p <<< $svg) # replace + with p
    simplifySVG $name $svg

    # lichess
    chessieces=("p" "r" "cn" "b" "q" "k")
    if [[ ${chessPieces[*]} =~ $key ]] then
      cp=$p
      if [[ $key = "cn" ]]; then cp=knight; fi # Use shogi 马 not 桂
      emitcss "piece.$cp.white" $B64w >> $LICHESSCSS
      emitcss "piece.$cp.black" $B64b >> $LICHESSCSS
      if [[ $key = "q" || $key = "cn" ]] then continue; fi
    fi

    # pychess
    p=$(tr + p <<< $key)
    # elem of a bash array is idiotically a regex
    cannonPieces=("a" "u" "i" "c") # "soldier" # silver,gold,iron,copper
    csp=$p
    if [ $key != "p" ]; then
     if [ $key = "soldier" ]; then csp="p"; fi # ! will continue loop
     emitcss ".cannonshogi piece.$csp-piece.white.ally"  $B64b >> $CannonShogiCSS
     emitcss ".cannonshogi piece.$csp-piece.white.enemy" $B64b >> $CannonShogiCSS
     emitcss ".cannonshogi piece.$csp-piece.black.ally"  $B64w >> $CannonShogiCSS
     emitcss ".cannonshogi piece.$csp-piece.black.enemy" $B64w >> $CannonShogiCSS
     if [[ "${cannonPieces[*]}" =~ "$key" || $key = soldier ]]; then continue; fi
    fi

    # pychess
    emitcss ".shogi piece.$p-piece.white.ally"  $B64b >> $OCSS
    emitcss ".shogi piece.$p-piece.white.enemy" $B64b >> $OCSS
    emitcss ".shogi piece.$p-piece.black.ally"  $B64w >> $OCSS
    emitcss ".shogi piece.$p-piece.black.enemy" $B64w >> $OCSS

    # lishogi
    emitcss "piece.$p.sente,
    .v-kyotoshogi piece.$p.sente,
    .v-kyotoshogi .sg-wrap.orientation-sente piece.$p.sente,
    .v-kyotoshogi .sg-wrap.orientation-gote piece.$p.sente" $B64b >> $LISHOGICSS
    emitcss "piece.$p.gote,
    .v-kyotoshogi piece.$p.gote,
    .v-kyotoshogi .sg-wrap.orientation-sente piece.$p.gote,
    .v-kyotoshogi .sg-wrap.orientation-gote piece.$p.gote" $B64w >> $LISHOGICSS

  done
  echo "}" >> $LICHESSCSS
  echo "}" >> $LISHOGICSS
  echo "}" >> $CannonShogiCSS
}

#genTori
genCHU
